### ISSUE TITLE
Rename plugin as reported by Plugin Name header

### ISSUE THREAD

**Issue by timbocode** [Classic-Commerce/cc-compat-woo#1]
Plugin name should not begin with 'WooCommerce' as this violates Automattic trademarks etc.

Plugin should be named "CC Compatibility for WooCommerce" or "CC Compat with WooCommerce".

File name should be left as woocommerce.php and must be located in woocommerce directory.

**Comment by bahiirwa** [comment]
Plugin should be named "CC Compatibility for WooCommerce"

**Comment by zulfgani** [comment]
"CC Compatibility for WooCommerce" implies we are making CC compatible with WC itself rather than making WC addons compatible with CC

I'd suggest "CC Compatibility with Woo Addons" or "CC Compatibility for Woo Addons" as the plugin name

**Comment by timbocode** [comment]
That's a fair point @zulfgani . I would therefore suggest we go with your second option: "CC Compatibility for Woo Addons".

**Comment by bahiirwa** [comment]
Fixed in #2
