### ISSUE TITLE
Change UPDATE_SERVER constant

### ISSUE THREAD

**Issue by ghost** [Classic-Commerce/cc-compat-woo#14]
New address for plugin updates: officialplugins.classicpress.net.

Need to change UPDATE_SERVER constant in /includes/UpdateClient.class.php.

**Comment by ghost** [comment]
@timbocode - let me know when you have this set up and I'll do a PR for it.

**Comment by xxsimoxx** [comment]
Closing as in #19 UpdateClient is removed.
