### ISSUE TITLE
Add images to update process?

### ISSUE THREAD

**Issue by ghost** [Classic-Commerce/cc-compat-woo#15]
Not sure if this is necessary, but currently updating the cc-compat-woo plugin shows this:

![update](https://user-images.githubusercontent.com/46998578/102938460-7b8bad00-4500-11eb-8dd8-785312fd4e9a.jpg)

Do we want to add images? (I guess we would use the same as CC)

**Comment by timbocode** [comment]
Yes, I think an image would be better than the placeholder. Something like this perhaps??:

![cc-compat-icon](https://user-images.githubusercontent.com/4199514/103012105-fa99d900-4532-11eb-99db-6c3a2f5b60b1.jpg)

**Comment by ghost** [comment]
That's perfect!

**Comment by timbocode** [comment]
Closed by #16
