### ISSUE TITLE
Publish to packagist for use with composer

### ISSUE THREAD

**Issue by redtux** [Classic-Commerce/cc-compat-woo#17]
Hi, I am using bedrock and would like to install this plugin just like I do with Classic Commerce (see https://github.com/ClassicPress-plugins/classic-commerce/issues/239).

```sh
composer create-project roots/bedrock
cd bedrock
composer remove roots/wordpress
composer require classicpress/classicpress:~1.0
composer require classicpress-research/classic-commerce
```

Maybe you could publish a package to packagist or wpackagist? :heart: 

Thank you for your great efforts to preserve our freedoms and a happy new year! :tada:

**Comment by timbocode** [comment]
Hi @redtux thanks for the comment. This is something we'd be happy to look at. 

If approved (and I personally can't see why it wouldn't), then hopefully we'll be able to push this through with our next release of the plugin due within the next week or two.

Thanks again.

**Comment by redtux** [comment]
Great, this would be cool for all CP plugins, as most of them are not (yet) on packagist/wpackagist. Thanks a lot! 🎉

**Comment by nylen** [comment]
There is a preliminary version available now:

```
composer require timbocode/cc-compat-woo
```

Thanks @timbocode for setting up this test, I can confirm it works so I will leave it to you to do the same thing here on the main repo, and I can publish this on packagist when you tell me it's ready.

@redtux let us know which other plugins you need available on packagist and we'll look into it.

**Comment by redtux** [comment]
@nylen & @timbocode, thank you so much! :heart_eyes_cat:
I can confirm the package installs fine in a multi-site network using bedrock. :rocket:

Thank you for your kind offer! As for CC, I guess [Classic SEO](https://github.com/ClassicPress-plugins/classicpress-seo) would be great to start with.

#### Extended wishlist :)
Except [CC](https://packagist.org/packages/classicpress-research/classic-commerce) and [qTranslate-XT](https://packagist.org/packages/qtranslate/qtranslate-xt), I can find no CP plugins on packagist (or wpackagist), so I guess all plugins mentioned in the [plugins directory](https://directory.classicpress.net/plugins) would be good candidates.

Xmas is already over, but my personal preferences would be (in no particular order):
- [CP Endorse](https://github.com/khacoder/endorse) by @khacoder
- [CP Enriched Editor](https://github.com/codepotent/Enriched-Editor) by @codepotent
- [CP Markdown](https://github.com/azurecurve/azrcrv-markdown) by @azurecurve
- [CP Sidebar Login](https://github.com/azurecurve/azrcrv-sidebar-login) by @azurecurve
- [CP To Twitter](https://github.com/azurecurve/azrcrv-to-twitter) by @azurecurve
