### ISSUE TITLE
Change folder name on plugin download and activate it.

### ISSUE THREAD

**Issue by bahiirwa** [Classic-Commerce/cc-compat-woo#3]
As agreed in https://github.com/ClassicPress-research/classic-commerce/issues/131#issuecomment-565746774

1. We have delegated the uninstallation of the WooCommerce plugin to the website owner.
1. This plugin on install and activation runs under the folder named **cc-compat-woo** with file **woocommerce.php**
1. We need to rewrite its name to folder named **woocommerce** with file **woocommerce.php**
1. Issue arises - CP will reocgnize the that plugin **cc-compat-woo/woocommerce.php** is no longer active in the plugins_options array. With this, the newly renamed  **woocommerce*/woocommerce.php** won't work. It is inactive until activated again.
1. The Challenge is rename the folder and activate it. 

Of course this is easy for an experiences developer to use a command line and accomplish all these tasks. How do we get the ordinary user who downloaded this plugin to do these tasks in one click of the button?

**Comment by timbocode** [comment]
I've been thinking about this too and came to the conclusion that perhaps the easiest thing to do is to rename the repo from **cc-compat-woo** to **woocommerce**. I know this isn't ideal but in the interests of keeping things simple, it would seem the most reasonable option to me?

**Comment by bahiirwa** [comment]
Solution: changing repo name.

**Comment by timbocode** [comment]
Temporarily reopening this further to Slack discussions.

Repo name to stay `cc-compat-woo`.

Use the following command to create an archive that extracts to `woocommerce/woocommerce.php`:

`git archive --prefix=woocommerce/ -o "woocommerce.zip" HEAD`

and then upload this to GitHub when a release is created.

**Comment by bahiirwa** [comment]
As advised, we need to make this a bash script.

**Comment by timbocode** [comment]
Closed with issue #7
